import { makeDictionary } from '@/lib/i18n/locales/factory';

export default makeDictionary({
  locale: 'es',
  site: { homeTitle: 'Herramientas de tiempo y codificacion para desarrolladores', homeDescription: 'Herramientas rapidas para timestamps, UTC, JSON, Base64, URL, regex y cron en el navegador.', developerToolkit: 'Kit de herramientas para desarrolladores' },
  nav: { home: 'Inicio', unixConverter: 'Conversor Unix', guides: 'Guias', allTools: 'Todas las herramientas', toolDirectory: 'Directorio de herramientas', quickAccess: 'Acceso rapido', language: 'Idioma' },
  ui: { openTool: 'Abrir herramienta', copy: 'Copiar', copied: 'Copiado', input: 'Entrada', output: 'Salida', relatedTools: 'Herramientas relacionadas', faq: 'FAQ', tool: 'Herramienta', definition: 'Definicion y contexto practico', steps: 'Explicacion paso a paso', examples: 'Ejemplos', useCases: 'Casos de uso comunes', toolsByCategory: 'Herramientas por categoria', recentTools: 'Herramientas recientes', popularTools: 'Herramientas populares' },
  home: { h1: 'Herramientas DevTimeKit para desarrolladores', intro: 'Convierte, inspecciona, codifica, decodifica y valida formatos comunes directamente en el navegador.', sections: [{ title: 'Para que sirve DevTimeKit', paragraphs: ['DevTimeKit reune utilidades para timestamps Unix, UTC, ISO 8601, JSON, Base64, URL, expresiones regulares y cron.', 'Cada pagina combina una herramienta usable con explicaciones claras para desarrolladores, buscadores y motores de respuesta con IA.'] }, { title: 'Por que usar herramientas en el navegador', paragraphs: ['Muchos errores pequenos, como mezclar segundos y milisegundos o usar JSON invalido, pueden bloquear una investigacion.', 'Pegar un valor, revisar el resultado y copiar la salida acelera el trabajo con APIs, tickets y pruebas.'] }], faq: [{ q: 'Son gratis estas herramientas?', a: 'Si. DevTimeKit es una coleccion gratuita de herramientas en el navegador.' }, { q: 'Necesitan backend?', a: 'No. Las conversiones interactivas se ejecutan en tu navegador.' }] },
  titles: { '/utc-to-local': 'UTC a hora local', '/local-to-utc': 'Hora local a UTC', '/iso8601-parser': 'Parser ISO 8601', '/json-formatter': 'Formateador JSON', '/base64-encode': 'Codificar Base64', '/base64-decode': 'Decodificar Base64', '/url-encode': 'Codificar URL', '/url-decode': 'Decodificar URL', '/regex-tester': 'Probador Regex', '/cron-expression-generator': 'Generador de expresiones Cron' },
  phrases: { description: (title) => `${title} es una herramienta rapida en el navegador con salida copiable y ejemplos practicos.`, definition: (title) => [`${title} ayuda a inspeccionar, convertir y validar formatos usados a diario en desarrollo. Es util para depurar APIs, escribir documentacion y preparar pruebas.`, 'La pagina combina una utilidad interactiva con una explicacion estructurada para que tambien funcione como referencia clara.', 'El flujo recomendado es validar la entrada, leer los errores temprano y copiar solo la salida que coincide con tu API o entorno.'], steps: (title) => [`Abre ${title} y pega el valor que quieres revisar.`, 'Comprueba la salida y cualquier mensaje de error.', 'Copia el resultado en codigo, una peticion API, una prueba o documentacion.'], examples: (title) => [`${title} puede usarse al depurar un payload de API.`, 'La salida copiada puede convertirse en fixture o ejemplo de documentacion.', 'Los mensajes de validacion ayudan a detectar formato incorrecto.'], useCases: () => ['Depurar peticiones y respuestas de API.', 'Preparar ejemplos legibles para documentacion.', 'Revisar valores antes de usarlos en pruebas o configuracion.'], faq: (title) => [{ q: `${title} envia datos a un servidor?`, a: 'No. La herramienta se ejecuta en el navegador.' }, { q: `Cuando deberia usar ${title}?`, a: 'Cuando necesites inspeccionar, convertir, validar o copiar un valor durante desarrollo.' }] }
});
