import { makeDictionary } from '@/lib/i18n/locales/factory';

export default makeDictionary({
  locale: 'hi',
  site: { homeTitle: 'डेवलपर समय और एन्कोडिंग टूल', homeDescription: 'टाइमस्टैम्प, UTC, JSON, Base64, URL, regex और cron के लिए तेज ब्राउजर टूल।', developerToolkit: 'डेवलपर टूलकिट' },
  nav: { home: 'होम', unixConverter: 'Unix कन्वर्टर', guides: 'गाइड', allTools: 'सभी टूल', toolDirectory: 'टूल डायरेक्टरी', quickAccess: 'त्वरित लिंक', language: 'भाषा' },
  ui: { openTool: 'टूल खोलें', copy: 'कॉपी', copied: 'कॉपी हुआ', input: 'इनपुट', output: 'आउटपुट', relatedTools: 'संबंधित टूल', faq: 'FAQ', tool: 'टूल', definition: 'परिभाषा और व्यवहारिक संदर्भ', steps: 'स्टेप-बाय-स्टेप説明', examples: 'उदाहरण', useCases: 'सामान्य उपयोग', toolsByCategory: 'श्रेणी के अनुसार टूल', recentTools: 'नए टूल', popularTools: 'लोकप्रिय टूल' },
  home: { h1: 'DevTimeKit डेवलपर टूल', intro: 'ब्राउजर में सामान्य डेवलपर डेटा फॉर्मेट को कन्वर्ट, जांच, एन्कोड, डिकोड और वैलिडेट करें।', sections: [{ title: 'DevTimeKit किस काम आता है', paragraphs: ['DevTimeKit Unix timestamp, UTC, ISO 8601, JSON, Base64, URL, regex और cron expression के लिए उपयोगी टूल देता है।', 'हर पेज पहले काम करने वाला टूल देता है और फिर साफ संरचित説明 देता है, ताकि डेवलपर, search engines और AI answer engines इसे आसानी से समझ सकें।'] }, { title: 'ब्राउजर टूल क्यों उपयोगी हैं', paragraphs: ['सेकंड और मिलीसेकंड मिलाना, invalid JSON, या double encoded URL जैसे छोटे मुद्दे debugging में समय ले सकते हैं।', 'आप value paste करते हैं, result देखते हैं, output copy करते हैं और वापस code, ticket या API client में चले जाते हैं।'] }], faq: [{ q: 'क्या ये टूल मुफ्त हैं?', a: 'हां। DevTimeKit मुफ्त browser-based developer tools का collection है।' }, { q: 'क्या backend चाहिए?', a: 'नहीं। interactive conversion browser में चलता है।' }] },
  titles: { '/utc-to-local': 'UTC से Local Time', '/local-to-utc': 'Local Time से UTC', '/iso8601-parser': 'ISO 8601 Parser', '/json-formatter': 'JSON Formatter', '/base64-encode': 'Base64 Encode', '/base64-decode': 'Base64 Decode', '/url-encode': 'URL Encode', '/url-decode': 'URL Decode', '/regex-tester': 'Regex Tester', '/cron-expression-generator': 'Cron Expression Generator' },
  phrases: { description: (title) => `${title} एक तेज browser-based developer tool है जिसमें copy-ready output और practical examples मिलते हैं।`, definition: (title) => [`${title} common development values को inspect, convert और validate करने में मदद करता है। यह API debugging, documentation और test data preparation के लिए उपयोगी है।`, 'यह पेज interactive utility और structured explanation दोनों देता है, इसलिए यह काम करने वाले tool और reference page दोनों की तरह उपयोगी है।', 'अच्छा workflow है: input format समझें, error जल्दी देखें, और वही output copy करें जो आपके API, database या runtime के लिए सही हो।'], steps: (title) => [`${title} खोलें और value paste करें।`, 'Output और error message देखें।', 'Result को code, API request, test fixture या documentation में copy करें।'], examples: (title) => [`${title} API payload debugging में काम आता है।`, 'Copied output test fixture या documentation example बन सकता है।', 'Validation feedback input format की समस्या पहचानने में मदद करता है।'], useCases: () => ['API requests और responses debug करना।', 'Documentation के लिए readable examples बनाना।', 'Tests, logs या config में value डालने से पहले check करना।'], faq: (title) => [{ q: `क्या ${title} data server पर भेजता है?`, a: 'नहीं। tool browser में चलता है।' }, { q: `${title} कब इस्तेमाल करना चाहिए?`, a: 'जब development के दौरान value inspect, convert, validate या copy करनी हो।' }] }
});
