import { makeDictionary } from '@/lib/i18n/locales/factory';

export default makeDictionary({
  locale: 'ko',
  site: { homeTitle: '개발자를 위한 시간 및 인코딩 도구', homeDescription: '타임스탬프, UTC, JSON, Base64, URL, 정규식, cron을 브라우저에서 빠르게 다루는 도구 모음입니다.', developerToolkit: '개발자 도구 모음' },
  nav: { home: '홈', unixConverter: 'Unix 변환', guides: '가이드', allTools: '전체 도구', toolDirectory: '도구 목록', quickAccess: '빠른 이동', language: '언어' },
  ui: { openTool: '도구 열기', copy: '복사', copied: '복사됨', input: '입력', output: '출력', relatedTools: '관련 도구', faq: 'FAQ', tool: '도구', definition: '정의와 실무 맥락', steps: '단계별 설명', examples: '예시', useCases: '일반적인 사용 사례', toolsByCategory: '카테고리별 도구', recentTools: '최근 도구', popularTools: '인기 도구' },
  home: { h1: 'DevTimeKit 개발자 도구', intro: '브라우저에서 일반적인 개발 데이터 형식을 변환, 검사, 인코딩, 디코딩, 검증합니다.', sections: [{ title: 'DevTimeKit의 용도', paragraphs: ['DevTimeKit은 Unix 타임스탬프, UTC 변환, ISO 8601 파싱, JSON 포맷팅, Base64, URL 인코딩, 정규식, cron 표현식을 다루는 도구 모음입니다.', '각 페이지는 실제 도구와 구조화된 설명을 함께 제공해 개발자와 검색 엔진, AI 답변 엔진이 이해하기 쉽습니다.'] }, { title: '브라우저 기반 도구가 유용한 이유', paragraphs: ['초와 밀리초 혼동, 잘못된 JSON, 이중 인코딩된 URL 같은 작은 실수도 디버깅 시간을 크게 늘릴 수 있습니다.', '값을 붙여넣고 결과를 확인한 뒤 복사하여 코드, 티켓, 터미널, API 클라이언트로 바로 돌아갈 수 있습니다.'] }], faq: [{ q: '무료인가요?', a: '네. DevTimeKit은 무료 브라우저 기반 개발자 도구입니다.' }, { q: '백엔드가 필요한가요?', a: '아니요. 대화형 변환은 브라우저에서 실행됩니다.' }] },
  titles: { '/utc-to-local': 'UTC를 로컬 시간으로 변환', '/local-to-utc': '로컬 시간을 UTC로 변환', '/iso8601-parser': 'ISO 8601 파서', '/json-formatter': 'JSON 포매터', '/base64-encode': 'Base64 인코딩', '/base64-decode': 'Base64 디코딩', '/url-encode': 'URL 인코딩', '/url-decode': 'URL 디코딩', '/regex-tester': '정규식 테스터', '/cron-expression-generator': 'Cron 표현식 생성기' },
  phrases: { description: (title) => `${title}는 복사 가능한 출력과 실용적인 예시를 제공하는 빠른 브라우저 개발자 도구입니다.`, definition: (title) => [`${title}는 개발 중 자주 만나는 값을 확인, 변환, 검증하는 데 도움을 줍니다. API 디버깅, 문서 작성, 테스트 데이터 준비에 적합합니다.`, '이 페이지는 상호작용 도구와 개념 설명을 함께 제공하여 실무 도구이자 참고 자료로 사용할 수 있습니다.', '안전한 흐름은 입력 형식을 확인하고 오류를 일찍 파악한 뒤 API나 실행 환경에 맞는 출력만 복사하는 것입니다.'], steps: (title) => [`${title}를 열고 확인할 값을 붙여넣습니다.`, '출력과 오류 메시지를 확인합니다.', '결과를 코드, API 요청, 테스트 또는 문서에 복사합니다.'], examples: (title) => [`${title}는 API payload 디버깅에 사용할 수 있습니다.`, '복사한 출력은 테스트 fixture나 문서 예시로 재사용할 수 있습니다.', '검증 메시지는 입력 오류와 형식 차이를 구분하는 데 도움이 됩니다.'], useCases: () => ['API 요청과 응답 디버깅.', '문서용 읽기 쉬운 예시 준비.', '테스트, 로그, 설정에 넣기 전 값 확인.'], faq: (title) => [{ q: `${title}가 데이터를 서버로 보내나요?`, a: '아니요. 도구는 브라우저에서 실행됩니다.' }, { q: `${title}는 언제 사용하나요?`, a: '개발 중 값을 검사, 변환, 검증, 복사해야 할 때 사용합니다.' }] }
});
