import { makeDictionary } from '@/lib/i18n/locales/factory';

export default makeDictionary({
  locale: 'vi',
  site: { homeTitle: 'Cong cu thoi gian va ma hoa cho lap trinh vien', homeDescription: 'Cong cu nhanh cho timestamp, UTC, JSON, Base64, URL, regex va cron ngay trong trinh duyet.', developerToolkit: 'Bo cong cu lap trinh vien' },
  nav: { home: 'Trang chu', unixConverter: 'Chuyen doi Unix', guides: 'Huong dan', allTools: 'Tat ca cong cu', toolDirectory: 'Danh muc cong cu', quickAccess: 'Truy cap nhanh', language: 'Ngon ngu' },
  ui: { openTool: 'Mo cong cu', copy: 'Sao chep', copied: 'Da sao chep', input: 'Dau vao', output: 'Dau ra', relatedTools: 'Cong cu lien quan', faq: 'FAQ', tool: 'Cong cu', definition: 'Dinh nghia va ngu canh thuc te', steps: 'Giai thich tung buoc', examples: 'Vi du', useCases: 'Truong hop su dung pho bien', toolsByCategory: 'Cong cu theo danh muc', recentTools: 'Cong cu moi', popularTools: 'Cong cu pho bien' },
  home: { h1: 'Cong cu DevTimeKit cho lap trinh vien', intro: 'Chuyen doi, kiem tra, ma hoa, giai ma va xac thuc cac dinh dang du lieu phat trien pho bien.', sections: [{ title: 'DevTimeKit dung de lam gi', paragraphs: ['DevTimeKit gom cac cong cu cho Unix timestamp, UTC, ISO 8601, JSON, Base64, URL, regex va cron.', 'Moi trang co cong cu dung duoc ngay va phan giai thich ro rang de lap trinh vien, cong cu tim kiem va AI de dang hieu.'] }, { title: 'Vi sao cong cu tren trinh duyet huu ich', paragraphs: ['Nhung loi nho nhu nham giua giay va mili giay, JSON sai cu phap, hay URL bi encode hai lan co the ton nhieu thoi gian debug.', 'Ban chi can dan gia tri, xem ket qua, sao chep dau ra va quay lai code, ticket hoac API client.'] }], faq: [{ q: 'Cac cong cu nay co mien phi khong?', a: 'Co. DevTimeKit la bo cong cu mien phi chay tren trinh duyet.' }, { q: 'Co can backend khong?', a: 'Khong. Cac thao tac chuyen doi chay trong trinh duyet.' }] },
  titles: { '/utc-to-local': 'UTC sang gio dia phuong', '/local-to-utc': 'Gio dia phuong sang UTC', '/iso8601-parser': 'Bo phan tich ISO 8601', '/json-formatter': 'Dinh dang JSON', '/base64-encode': 'Ma hoa Base64', '/base64-decode': 'Giai ma Base64', '/url-encode': 'Ma hoa URL', '/url-decode': 'Giai ma URL', '/regex-tester': 'Kiem thu Regex', '/cron-expression-generator': 'Tao bieu thuc Cron' },
  phrases: { description: (title) => `${title} la cong cu nhanh tren trinh duyet voi dau ra de sao chep va vi du thuc te.`, definition: (title) => [`${title} giup kiem tra, chuyen doi va xac thuc du lieu thuong gap trong phat trien phan mem. Cong cu huu ich khi debug API, viet tai lieu va tao test case.`, 'Trang ket hop cong cu tuong tac voi noi dung giai thich co cau truc, nen phu hop ca cho cong viec hang ngay va tham khao.', 'Quy trinh tot la kiem tra dinh dang dau vao, doc thong bao loi som, roi sao chep dau ra phu hop voi API hoac moi truong cua ban.'], steps: (title) => [`Mo ${title} va dan gia tri can xu ly.`, 'Kiem tra dau ra va thong bao loi neu co.', 'Sao chep ket qua vao code, API request, test hoac tai lieu.'], examples: (title) => [`${title} co the dung khi debug API payload.`, 'Dau ra co the dung lam fixture hoac vi du tai lieu.', 'Thong bao loi giup phan biet du lieu sai dinh dang hay khac don vi.'], useCases: () => ['Debug request va response API.', 'Tao vi du de doc trong tai lieu.', 'Kiem tra gia tri truoc khi dua vao test, log hoac cau hinh.'], faq: (title) => [{ q: `${title} co gui du lieu len server khong?`, a: 'Khong. Cong cu chay trong trinh duyet.' }, { q: `Khi nao nen dung ${title}?`, a: 'Khi ban can kiem tra, chuyen doi, xac thuc hoac sao chep gia tri trong qua trinh phat trien.' }] }
});
